<?php

declare(strict_types=1);

namespace Juling\DevTools\Commands;

use Juling\DevTools\Support\SchemaTrait;
use think\console\Command;
use think\console\Input;
use think\console\input\Argument;
use think\console\Output;
use think\facade\View;

class GenModelCommand extends Command
{
    use SchemaTrait;

    private array $ignoreTables = ['migrations'];

    private bool $grouping = false;

    protected function configure(): void
    {
        $this->setName('gen:model')
            ->addArgument('grouping', Argument::OPTIONAL, 'generated by group', true)
            ->setDescription('Generate model class');
    }

    protected function execute(Input $input, Output $output): int
    {
        $this->grouping = boolval($input->getArgument('grouping'));

        $tables = $this->getTables();
        foreach ($tables as $row) {
            $tableName = implode('', $row);
            if (in_array($tableName, $this->ignoreTables)) {
                continue;
            }
            $columns = $this->getTableInfo($tableName);
            $this->modelTpl($tableName, $columns);
        }

        return 1;
    }

    private function modelTpl($tableName, $columns): void
    {
        $groupName = $this->getTableGroupName($tableName);
        $className = parse_name($tableName, 1);

        $primaryKeyStr = 'id';
        $primaryKey = $this->getPrimaryKeyType($columns);
        if (! empty($primaryKey) && $primaryKey['Field'] !== 'id') {
            $primaryKeyStr = $primaryKey['Field'];
        }

        $createdTime = false;
        $updatedTime = false;
        $softDelete = false;
        foreach ($columns as $column) {
            if ($column['Field'] === 'create_time') {
                $createdTime = true;
            }
            if ($column['Field'] === 'update_time') {
                $updatedTime = true;
            }
            if ($column['Field'] === 'delete_time') {
                $softDelete = true;
            }
        }

        $data = [
            'grouping' => $this->grouping,
            'groupName' => $groupName,
            'className' => $className,
            'tableName' => $tableName,
            'primaryKey' => $primaryKeyStr,
            'createdTime' => $createdTime,
            'updatedTime' => $updatedTime,
            'softDelete' => $softDelete,
            'columns' => $columns,
        ];

        $tpl = file_get_contents(__DIR__.'/stubs/model/model.stub');
        $content = View::display($tpl, $data);

        $dist = $this->grouping ? app_path('bundles/'.$groupName.'/model') : app_path('model');
        $this->ensureDirectoryExists($dist);
        file_put_contents($dist.'/'.$className.'Model.php', '<?php'."\n\n".$content);
    }
}
