<?php

declare(strict_types=1);

namespace Juling\DevTools\Commands;

use Juling\DevTools\Support\SchemaTrait;
use think\console\Command;
use think\console\Input;
use think\console\input\Argument;
use think\console\Output;
use think\facade\View;

class GenServiceCommand extends Command
{
    use SchemaTrait;

    private array $ignoreTables = ['migrations'];

    private bool $grouping = false;

    protected function configure(): void
    {
        $this->setName('gen:service')
            ->addArgument('grouping', Argument::OPTIONAL, 'generated by group', true)
            ->setDescription('Generate service class');
    }

    protected function execute(Input $input, Output $output): int
    {
        $this->grouping = boolval($input->getArgument('grouping'));

        $tables = $this->getTables();
        foreach ($tables as $row) {
            $tableName = implode('', $row);
            if (in_array($tableName, $this->ignoreTables)) {
                continue;
            }
            $this->serviceTpl($tableName);
        }

        return 1;
    }

    private function serviceTpl(string $tableName): void
    {
        $groupName = $this->getTableGroupName($tableName);
        $className = parse_name($tableName, 1);

        $data = [
            'grouping' => $this->grouping,
            'groupName' => $groupName,
            'className' => $className,
        ];
        $tpl = file_get_contents(__DIR__.'/stubs/service/service.stub');
        $content = View::display($tpl, $data);

        $dist = $this->grouping ? app_path('bundles/'.$groupName.'/service') : app_path('service');
        $this->ensureDirectoryExists($dist);
        file_put_contents($dist.'/'.$className.'BundleService.php', '<?php'."\n\n".$content);
    }
}
